package cfg

import (
	_ "embed"
	"fmt"
	"path/filepath"
	"strings"

	"github.com/damienbutt/figlet"

	"github.com/Norgate-AV/genlinx/internal/apw"
)

//go:embed LICENSE
var licenseText string

// Options configures the CFG build process, merging config file values with
// CLI flags. It is the Go equivalent of the TypeScript CfgOptions type.
type Options struct {
	RootDirectory             string
	OutputFileSuffix          string
	OutputLogFileSuffix       string
	OutputLogFileOption       string // "A" or "N"
	OutputLogConsoleOption    bool
	BuildWithDebugInformation bool
	BuildWithSource           bool
	IncludePath               []string
	ModulePath                []string
	LibraryPath               []string
	All                       bool
	Verbose                   bool
}

// Builder generates the content of a NetLinx build CFG file from a parsed APW
// workspace. It is the Go equivalent of the TypeScript CfgBuilder class.
type Builder struct {
	apw  *apw.APW
	opts *Options
	buf  strings.Builder
}

// NewBuilder returns a new Builder for the given workspace and options.
func NewBuilder(workspace *apw.APW, opts *Options) *Builder {
	return &Builder{
		apw:  workspace,
		opts: opts,
	}
}

// Build generates and returns the full CFG file contents.
func (b *Builder) Build() string {
	b.addBanner("NorgateAV")
	b.writeLine(";")
	b.addLicense()
	b.writeLine("; This file was generated by genlinx, https://github.com/Norgate-AV/genlinx")
	b.writeLine(";")

	b.addHeader([]string{
		"; Used by the NetLinx Compiler Console program (NLRC.EXE) that specifies",
		"; how to invoke the the NetLinx Compiler with a configuration file via a",
		"; command console window.",
		";",
		`;   > NLRC -C"C:\AMX Projects\build.cfg"`,
		";",
	})

	b.addMainRootDirectory()
	b.addSourceFiles()
	b.addLogFileOptions()
	b.addCompilerOptionOverrides()
	b.addAdditionalPaths()

	return b.buf.String()
}

// ---------------------------------------------------------------------------
// Low-level write helpers
// ---------------------------------------------------------------------------

func (b *Builder) writeLine(s string) {
	b.buf.WriteString(s)
	b.buf.WriteByte('\n')
}

func (b *Builder) writeBlankLine() {
	b.buf.WriteByte('\n')
}

// ---------------------------------------------------------------------------
// Section helpers
// ---------------------------------------------------------------------------

func (b *Builder) convertToComment(text string) string {
	lines := strings.Split(text, "\n")
	result := make([]string, len(lines))

	for i, line := range lines {
		if line != "" {
			result[i] = "; " + line
		} else {
			result[i] = ";"
		}
	}

	return strings.Join(result, "\n")
}

func (b *Builder) addBanner(text string) {
	banner, _ := figlet.Text(text)
	b.writeLine(b.convertToComment(banner))
}

func (b *Builder) addLicense() {
	b.writeLine(b.convertToComment(licenseText))
}

func (b *Builder) addHeader(contentLines []string) {
	b.writeLine(";------------------------------------------------------------------------------")

	for _, line := range contentLines {
		b.writeLine(line)
	}

	b.writeLine(";------------------------------------------------------------------------------")
}

// ---------------------------------------------------------------------------
// CFG sections (each mirrors a private method on the TS CfgBuilder)
// ---------------------------------------------------------------------------

func (b *Builder) addMainRootDirectory() {
	b.addHeader([]string{
		";",
		";  Main AXS Root Directory Reference",
		";",
	})

	rootDirectory := "-R"
	if b.opts.RootDirectory != "" {
		abs, err := filepath.Abs(b.opts.RootDirectory)
		if err == nil {
			rootDirectory = abs
		} else {
			rootDirectory = b.opts.RootDirectory
		}
	}

	b.writeLine(fmt.Sprintf("MainAXSRootDirectory=%s", rootDirectory))
	b.writeBlankLine()
}

func (b *Builder) addAxsFiles(files []apw.File) {
	for _, file := range files {
		b.writeLine(fmt.Sprintf("AXSFILE=%s", file.Path))
	}

	b.writeBlankLine()
}

func (b *Builder) addSourceFiles() {
	b.addHeader([]string{
		";",
		"; AXS files when specifying the MainAXSRootDirectory key above. You can have more",
		"; than one, order of the compile is as written.",
		";",
	})

	b.addAxsFiles(b.apw.ModuleFiles())
	b.addAxsFiles(b.apw.MasterSrcFiles())
}

func (b *Builder) addLogFileOptions() {
	b.addHeader([]string{
		";",
		"; Output Log File and Log File Options.",
		";",
		"; OutputLogFile=        <--: Output log file name",
		";",
		";    Fully qualified file name (no quotes are needed)",
		";    If no OutputLogFile key present, then by default, log to the console",
		";    window.  Unless the OptionLogConsoleOptions= is specified (see below).",
		";",
		"; OutputLogFileOption=  <--: Output log file option",
		";",
		";    A = Append status to the output file. If file does not exist,",
		";        then the program will create a new one.",
		";    N = Create a new output file. Overwrites if the file already exists.",
		";",
		";  If no OutputLogFileOption key present, then the default is N.",
		";",
		"; OutputLogConsoleOption= <--: Output Log to the Console",
		";",
		";    Y = Send log info to the console.",
		";    N = Do no send log info to the console.",
	})

	outputLogFile := fmt.Sprintf("%s.%s", b.apw.ID(), b.opts.OutputLogFileSuffix)
	consoleOption := "N"

	if b.opts.OutputLogConsoleOption {
		consoleOption = "Y"
	}

	b.writeLine(fmt.Sprintf("OutputLogFile=%s", outputLogFile))
	b.writeLine(fmt.Sprintf("OutputLogFileOption=%s", b.opts.OutputLogFileOption))
	b.writeLine(fmt.Sprintf("OutputLogConsoleOption=%s", consoleOption))
	b.writeBlankLine()
}

func (b *Builder) addCompilerOptionOverrides() {
	b.addHeader([]string{
		";",
		"; NetLinx Compiler Option Overrides",
		";",
		";   Ability to override the NetLinx Studio Compiler options that are defined",
		";   within NetLinx Studio.",
		";",
		";   Y = Yes   N = No",
		";",
		"; Comment these options out if you want to use the NetLinx Studio options.",
	})

	debugInfo := "N"
	if b.opts.BuildWithDebugInformation {
		debugInfo = "Y"
	}

	withSource := "N"
	if b.opts.BuildWithSource {
		withSource = "Y"
	}

	b.writeLine(fmt.Sprintf("BuildWithDebugInformation=%s", debugInfo))
	b.writeLine(fmt.Sprintf("BuildWithSource=%s", withSource))
	b.writeBlankLine()
}

func (b *Builder) addAdditionalIncludePaths() {
	// Merge workspace include paths (mirrors TS: options.includePath.push(...apw.includePath))
	combined := deduplicate(append(b.opts.IncludePath, b.apw.IncludePath()...))

	for _, p := range combined {
		b.writeLine(fmt.Sprintf("AdditionalIncludePath=%s", p))
	}

	b.writeBlankLine()
}

func (b *Builder) addAdditionalModulePaths() {
	// Merge workspace module paths
	combined := deduplicate(append(b.opts.ModulePath, b.apw.ModulePath()...))

	for _, p := range combined {
		b.writeLine(fmt.Sprintf("AdditionalModulePath=%s", p))
	}

	b.writeBlankLine()
}

func (b *Builder) addAdditionalLibraryPaths() {
	for _, p := range deduplicate(b.opts.LibraryPath) {
		b.writeLine(fmt.Sprintf("AdditionalLibraryPath=%s", p))
	}

	b.writeBlankLine()
}

func (b *Builder) addAdditionalPaths() {
	b.addHeader([]string{
		"; Additional Paths",
		";",
		"; If you need to specify additional paths for the NetLinx compiler, you can add",
		"; the following keys:",
		";",
		";    AdditionalIncludePath=",
		";    AdditionalLibraryPath=",
		";    AdditionalModulePath=",
		";",
		"; You can specify upto 50 additional paths for each type (one directory per",
		"; key upto 50 keys per type).  No quotes are needed for the directory names.",
	})

	b.addAdditionalIncludePaths()
	b.addAdditionalModulePaths()
	b.addAdditionalLibraryPaths()
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

func deduplicate(items []string) []string {
	seen := make(map[string]bool)
	var result []string

	for _, item := range items {
		key := strings.ReplaceAll(item, "\\", "/")
		if !seen[key] {
			result = append(result, filepath.FromSlash(item))
			seen[key] = true
		}
	}

	return result
}
